### ISSUE TITLE
Clarify installation requirements

### ISSUE THREAD

**Issue by parikshitbajpai** [ThibaultFillion/strengths#6]
During my review on openjournals/joss-reviews#6495, I followed the instruction to install Strengths using pip but forgot to install requirements using `pip install -r requirements.txt`. This meant the tests failed when I ran them the first time. This can easily happen when using separate condo / virtual environments to avoid dependency conflicts between various codes. 

I suggest either adding the installing requirements step to the instructions in readme or adding dependencies to `setuptools` configuration file so that the required packages get installed alongside strengths.

**Comment by ThibaultFillion** [comment]
Sorry for the inconvenience, thank you for telling me.
I added instructions to the readme file.

**Comment by parikshitbajpai** [comment]
Thanks for adding the instructions. I noticed that the instructions for `matplotlib` have `numpy` in them.

Alternatively, I would suggest keeping a single line of text that says install requirements using `pip install -r requirements.txt`. This way you can ensure that all the requirements are installed in a single step and makes managing requirements easier as the project grows and dependencies increase.

**Comment by ThibaultFillion** [comment]
No problem. Indeed, it seems matplotlib requires numpy.
Thank you for your suggestion, this will indeed make the readme and the documentation easier to maintain,
I will make the change now.
